# Generated by Django 3.0.2 on 2021-08-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('admin', models.CharField(max_length=50)),
                ('employee', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('admin', models.CharField(max_length=50)),
                ('employee', models.CharField(max_length=50)),
                ('project', models.CharField(max_length=500)),
                ('deadline', models.CharField(max_length=20)),
            ],
        ),
    ]
